### ISSUE TITLE
source?

### ISSUE THREAD

**Issue by srid** [deltam/clj-epub#1]
Have you forgot to push the source for the package you have uploaded at clojars?
http://clojars.org/clj-epub/clj-epub

When I googled for "clojure epub library" your library comes up, but there is no source even though it appears that you intended to open source it.

**Comment by deltam** [comment]
Thanks for reminding me I forgot to work!

This code is used on "text2epub-clj". I was forgot separating code from that.
http://github.com/deltam/text2epub-clj

I was pushed code and uploaded jar to Clojars. Can you check this?

**Comment by srid** [comment]
Ok, great! 

Just curious, have you checked out [epublib](http://srid.github.com/blog/2011/09/generating-epub-in-clojure/)?

**Comment by deltam** [comment]
I don't know "epublib", but it seems useful.  

When I was started to develop "clj-epub", I know little for EPUB library.
Now, I've gonna have to re-survey for that.

Thank you for good information!
